# Bluestock NIFTY100 Financial Analytics

## Sprint 1 – Day 3

# Data Cleaning & Data Quality Preparation

This notebook performs data cleaning before validation and database loading.

### Objectives

- Remove duplicate records
- Handle missing values
- Standardize company identifiers
- Clean text columns
- Convert numeric columns
- Save cleaned datasets

In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

In [5]:
ROOT = Path("../")

PROCESSED = ROOT / "data" / "processed"

In [6]:
companies = pd.read_csv(PROCESSED / "companies_clean.csv")
profit = pd.read_csv(PROCESSED / "profitandloss_clean.csv")
balance = pd.read_csv(PROCESSED / "balancesheet_clean.csv")
cashflow = pd.read_csv(PROCESSED / "cashflow_clean.csv")
analysis = pd.read_csv(PROCESSED / "analysis_clean.csv")
ratios = pd.read_csv(PROCESSED / "financial_ratios_clean.csv")

In [7]:
datasets = {
    "Companies": companies,
    "Profit & Loss": profit,
    "Balance Sheet": balance,
    "Cash Flow": cashflow,
    "Analysis": analysis,
    "Financial Ratios": ratios
}

for name, df in datasets.items():
    print(f"{name}: {df.shape}")

Companies: (92, 12)
Profit & Loss: (1276, 15)
Balance Sheet: (1312, 13)
Cash Flow: (1187, 7)
Analysis: (20, 6)
Financial Ratios: (1184, 16)

In [8]:
for name, df in datasets.items():
    print("\n" + "=" * 50)
    print(name)
    print(df.isnull().sum())

==================================================
Companies
id                 0
company_logo       1
company_name       0
chart_link         0
about_company      0
website            1
nse_profile        1
bse_profile        1
face_value         1
book_value         1
roce_percentage    1
roe_percentage     2
dtype: int64

==================================================
Profit & Loss
id                     0
company_id             0
year                 100
sales                  0
expenses               0
operating_profit      13
opm_percentage        15
other_income           0
interest               0
depreciation           0
profit_before_tax      0
tax_percentage        95
net_profit             0
eps                    5
dividend_payout      103
dtype: int64

==================================================
Balance Sheet
id                   0
company_id           0
year                 0
equity_capital       0
reserves             0
borrowings           0
other_liabilities    0
total_liabilities    0
fixed_assets         0
cwip                 0
investments          0
other_asset          0
total_assets         0
dtype: int64

==================================================
Cash Flow
id                    0
company_id            0
year                  0
operating_activity    2
investing_activity    2
financing_activity    2
net_cash_flow         2
dtype: int64

==================================================
Analysis
id                          0
company_id                  0
compounded_sales_growth     0
compounded_profit_growth    0
stock_price_cagr            0
roe                         0
dtype: int64

==================================================
Financial Ratios
id                              0
company_id                      0
year                            0
net_profit_margin_pct           1
operating_profit_margin_pct    61
return_on_equity_pct            0
debt_to_equity                  0
interest_coverage              93
asset_turnover                  1
free_cash_flow_cr               2
capex_cr                        2
earnings_per_share              4
book_value_per_share            0
dividend_payout_ratio_pct       4
total_debt_cr                   0
cash_from_operations_cr         2
dtype: int64

In [9]:
for name, df in datasets.items():

    print("\n" + "="*70)
    print(name)

    missing = df[df.isnull().any(axis=1)]

    print("Rows with Missing Values :", len(missing))

    display(missing.head())

======================================================================
Companies
Rows with Missing Values : 3

,id,company_logo,company_name,chart_link,about_company,website,nse_profile,bse_profile,face_value,book_value,roce_percentage,roe_percentage
46,INDIGO,https://rb.gy/rv6gr8,Interglobe Aviation Ltd,https://in.tradingview.com/chart/?symbol=NSE%3...,Interglobe Aviation Ltd (Indigo) is India's la...,http://www.goindigo.in/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/int...,10.0,97.0,24.5,NaN
61,LTIM,NaN,LTIMindtree Ltd,https://mkt.in/static/mkt-icons/nifty100/ABB.png,LTIMindtree Limited is an Indian multinational...,https://www.ltimindtree.com/,https://www.nseindia.com/get-quotes/equity?sym...,https://www.bseindia.com/stock-share-price/lti...,1.0,711.0,34.1,26.04
91,TVSMOTOR,https://mkt.in/static/mkt-icons/nifty100/TVSMO...,TVS Motor Company Ltd,https://in.tradingview.com/chart/qGsydD2w/?sym...,'TVS Motor Company Ltd (TVSM) is engaged in ma...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

======================================================================
Profit & Loss
Rows with Missing Values : 120

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
12,73,ABB,NaN,6066,4519,1547.0,26.0,265,11,72,1728,NaN,1285,605.0,NaN
13,86,ADANIENSOL,2014.0,0,0,0.0,NaN,0,0,0,0,0.0,0,0.0,NaN
24,97,ADANIENSOL,NaN,22099,15507,6592.0,NaN,-844,3183,1912,653,NaN,589,6.0,NaN
37,110,ADANIENT,NaN,102311,88418,13893.0,14.0,1489,4150,3541,7691,NaN,6086,49.0,NaN
46,119,ADANIGREEN,NaN,10782,2682,8100.0,75.0,891,4959,2323,1709,NaN,1928,9.0,0.0

======================================================================
Balance Sheet
Rows with Missing Values : 0

Empty DataFrame
Columns: [id, company_id, year, equity_capital, reserves, borrowings, other_liabilities, total_liabilities, fixed_assets, cwip, investments, other_asset, total_assets]
Index: []

======================================================================
Cash Flow
Rows with Missing Values : 2

,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
487,550,HDFCLIFE,2013,NaN,NaN,NaN,NaN
488,551,HDFCLIFE,2014,NaN,NaN,NaN,NaN

======================================================================
Analysis
Rows with Missing Values : 0

Empty DataFrame
Columns: [id, company_id, compounded_sales_growth, compounded_profit_growth, stock_price_cagr, roe]
Index: []

======================================================================
Financial Ratios
Rows with Missing Values : 99

,id,company_id,year,net_profit_margin_pct,operating_profit_margin_pct,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,free_cash_flow_cr,capex_cr,earnings_per_share,book_value_per_share,dividend_payout_ratio_pct,total_debt_cr,cash_from_operations_cr
0,1,ABB,2012,8.77,12.0,22.41,0.0,NaN,1.8225,42.0,59.0,68.0,3.0810,25.0,0,101.0
1,2,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,93.0,3.7524,25.0,0,155.0
2,3,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,93.0,3.7524,25.0,0,0.0
3,4,ABB,2015,10.00,14.0,24.44,0.0,NaN,1.6659,28.0,187.0,108.0,4.4619,29.0,0,215.0
4,5,ABB,2015,10.00,14.0,24.44,0.0,NaN,1.6659,-1899.0,1864.0,108.0,4.4619,29.0,0,-35.0

In [11]:
for name, df in datasets.items():

    print("\n" + "=" * 70)
    print(name)

    print("Duplicate Rows :", df.duplicated().sum())

======================================================================
Companies
Duplicate Rows : 0

======================================================================
Profit & Loss
Duplicate Rows : 0

======================================================================
Balance Sheet
Duplicate Rows : 0

======================================================================
Cash Flow
Duplicate Rows : 0

======================================================================
Analysis
Duplicate Rows : 0

======================================================================
Financial Ratios
Duplicate Rows : 0

In [12]:
tables = {
    "Profit & Loss": profit,
    "Balance Sheet": balance,
    "Cash Flow": cashflow,
    "Financial Ratios": ratios
}

for name, df in tables.items():

    print("\n" + "=" * 70)
    print(name)

    dup = df[df.duplicated(subset=["company_id", "year"], keep=False)]

    print("Duplicate (company_id, year):", len(dup))

    if not dup.empty:
        display(dup.head(10))

======================================================================
Profit & Loss
Duplicate (company_id, year): 26

,id,company_id,year,sales,expenses,operating_profit,opm_percentage,other_income,interest,depreciation,profit_before_tax,tax_percentage,net_profit,eps,dividend_payout
47,120,ADANIPORTS,2013.0,3577,1195,2382.0,67.0,344,542,422,1762,7.0,1639,8.0,12.0
48,121,ADANIPORTS,2014.0,4830,1910,2919.0,60.0,685,977,649,1978,12.0,1741,8.0,12.0
49,122,ADANIPORTS,2015.0,6152,2250,3902.0,63.0,686,1175,912,2501,7.0,2324,11.0,10.0
50,123,ADANIPORTS,2016.0,7109,2532,4577.0,64.0,730,1124,1063,3119,9.0,2856,14.0,8.0
51,124,ADANIPORTS,2017.0,8439,3021,5418.0,64.0,1037,1116,1160,4179,7.0,3902,19.0,7.0
52,125,ADANIPORTS,2018.0,11323,4166,7157.0,63.0,844,1579,1188,5234,30.0,3690,18.0,11.0
53,126,ADANIPORTS,2019.0,10925,4330,6596.0,60.0,1289,1385,1373,5126,21.0,4045,19.0,1.0
54,127,ADANIPORTS,2020.0,11873,5926,5947.0,50.0,1928,1951,1680,4244,11.0,3785,19.0,17.0
55,128,ADANIPORTS,2021.0,12550,3862,8688.0,69.0,1967,2255,2107,6292,20.0,5049,25.0,20.0
56,129,ADANIPORTS,2022.0,17119,7591,9528.0,56.0,1832,2544,3099,5717,13.0,4953,23.0,22.0

======================================================================
Balance Sheet
Duplicate (company_id, year): 308

,id,company_id,year,equity_capital,reserves,borrowings,other_liabilities,total_liabilities,fixed_assets,cwip,investments,other_asset,total_assets
11,147,ABB,2024,21.0,3678,83,1411,5193,225,10,0,4958,5193
12,148,ABB,2024,21.0,3500,60,1481,5063,216,13,0,4834,5063
23,159,ADANIENSOL,2024,1115.0,11526,37070,8827,58538,38920,3003,766,15849,58538
24,160,ADANIENSOL,2024,1201.0,19784,39009,9113,69107,38186,4355,1608,24958,69107
36,181,ADANIENT,2024,114.0,38962,65310,56200,160586,65978,35180,8701,50728,160586
37,182,ADANIENT,2024,114.0,41782,80427,59445,181768,84751,29745,10322,56949,181768
45,199,ADANIGREEN,2024,1584.0,8250,64858,13394,88086,62284,6427,1515,17860,88086
46,200,ADANIGREEN,2024,1584.0,8992,67430,20252,98258,64632,14617,2331,16678,98258
58,212,ADANIPORTS,2024,432.0,52346,49470,14751,116999,75148,10936,4289,26627,116999
59,213,ADANIPORTS,2024,432.0,56744,50485,18354,126015,79136,13328,4489,29062,126015

======================================================================
Cash Flow
Duplicate (company_id, year): 70

,id,company_id,year,operating_activity,investing_activity,financing_activity,net_cash_flow
0,37,TCS,2013,11615.0,-6038.0,-5729.0,-152.0
1,38,TCS,2014,14751.0,-9452.0,-5673.0,-374.0
2,39,TCS,2015,19369.0,-1807.0,-17168.0,394.0
3,40,TCS,2016,19109.0,-5010.0,-9666.0,4433.0
4,41,TCS,2017,25223.0,-16895.0,-11026.0,-2698.0
5,42,TCS,2018,25067.0,3104.0,-26885.0,1286.0
6,43,TCS,2019,28593.0,1645.0,-27897.0,2341.0
7,44,TCS,2020,32369.0,8968.0,-39915.0,1422.0
8,45,TCS,2021,38802.0,-7956.0,-32634.0,-1788.0
9,46,TCS,2022,39949.0,-738.0,-33581.0,5630.0

======================================================================
Financial Ratios
Duplicate (company_id, year): 202

,id,company_id,year,net_profit_margin_pct,operating_profit_margin_pct,return_on_equity_pct,debt_to_equity,interest_coverage,asset_turnover,free_cash_flow_cr,capex_cr,earnings_per_share,book_value_per_share,dividend_payout_ratio_pct,total_debt_cr,cash_from_operations_cr
1,2,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,11.0,144.0,93.0,3.7524,25.0,0,155.0
2,3,ABB,2014,8.70,12.0,25.13,0.0,NaN,1.9982,0.0,0.0,93.0,3.7524,25.0,0,0.0
3,4,ABB,2015,10.00,14.0,24.44,0.0,NaN,1.6659,28.0,187.0,108.0,4.4619,29.0,0,215.0
4,5,ABB,2015,10.00,14.0,24.44,0.0,NaN,1.6659,-1899.0,1864.0,108.0,4.4619,29.0,0,-35.0
5,6,ABB,2016,9.76,14.0,21.34,0.0,138.3333,1.6176,172.0,77.0,120.0,5.6905,29.0,0,249.0
6,7,ABB,2016,9.76,14.0,21.34,0.0,138.3333,1.6176,728.0,816.0,120.0,5.6905,29.0,0,1544.0
7,8,ABB,2017,9.54,14.0,19.97,0.0,227.5000,1.4051,152.0,155.0,130.0,6.6048,31.0,0,307.0
8,9,ABB,2017,9.54,14.0,19.97,0.0,227.5000,1.4051,459.0,1730.0,130.0,6.6048,31.0,0,2189.0
9,10,ABB,2018,12.16,16.0,23.69,0.0,160.5000,1.3651,-62.0,215.0,189.0,8.0619,29.0,0,153.0
10,11,ABB,2018,12.16,16.0,23.69,0.0,160.5000,1.3651,-994.0,3192.0,189.0,8.0619,29.0,0,2198.0

In [13]:
print(companies[["id", "company_name"]].head(15))

            id                                       company_name
0          ABB                                   Abbott India Ltd
1   ADANIENSOL                         Adani Energy Solutions Ltd
2     ADANIENT                              Adani Enterprises Ltd
3   ADANIGREEN                             Adani Green Energy Ltd
4   ADANIPORTS            Adani Ports & Special Economic Zone Ltd
5   ADANIPOWER                                    Adani Power Ltd
6    AMBUJACEM                                 Ambuja Cements Ltd
7   APOLLOHOSP  Apollo Hospitals Chain of Indian private hospi...
8   ASIANPAINT  Asian Paints Indian Multi-National Paint and C...
9         ATGL                                Adani Total Gas Ltd
10    AXISBANK                                      Axis Bank Ltd
11  BAJAJ-AUTO                                     Bajaj Auto Ltd
12  BAJAJFINSV                                  Bajaj Finserv Ltd
13  BAJAJHLDNG                    Bajaj Holdings & Investment Ltd
14  BAJFINANCE                                  Bajaj Finance Ltd